# Dockerfile.custom_exporter
FROM python:3.11-slim
WORKDIR /app
COPY custom_exporter.py .
RUN pip install --no-cache-dir prometheus_client requests
ENV PORT=8000
CMD ["python","custom_exporter.py"]
